task:
  name: DFlex
  env:
    env_name: snu_humanoid
    no_grad: true
agent:
  name: LWAIL/DFlexAnt
  ddpg:
    max_agent_steps: 10000000
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [512, 256]
    critic_kwargs:
      mlp_kwargs:
        units: [256, 256]
  lwail:
    demos:
      path: "experts/demos/DFlex_snu_demos128_return6246_len929.pt"
      n_trajs: 8
      subsample_factor: 1 # upstream does no subsampling; 1 = no subsampling, >1 keeps every nth step
    input_type: state_state
    discriminator:
      mlp_kwargs:
        units: [256, 256]
    expert_batch_size: 2048
    policy_batch_size: 2048

logdir: "workdir/DFlexSNUHumanoid10M-LWAIL/$(date +%Y%m%d-%H%M%S.%2N)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 120

sweep:
  seed: [100, 110, 120, 1000, 1100, 1200]
  agent.lwail.demos.subsample_factor: 1
  agent.lwail.expert_batch_size: 2048
  agent.lwail.discriminator.iters: 30
  agent.lwail.gp_coef: 10
  agent.lwail.minus: true

spawner:
  runtime: "7h30m"
