task:
  name: DFlex
  env:
    env_name: snu_humanoid
agent:
  name: DFlexAntSAPO
  shac:
    max_epochs: 5000
    max_agent_steps: 10000000
    critic_optim_kwargs:
      lr: 5e-4
    target_critic_alpha: 0.995
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [512, 256]
    critic_kwargs:
      mlp_kwargs:
        units: [256, 256]
logdir: "workdir/DFlexSNUHumanoid10M-SAPO/$(date +%Y%m%d-%H%M%S.%2N)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 120

sweep:
  seed: [100, 110, 120, 130, 140]
