task:
  name: DFlex
  env:
    env_name: ant
agent:
  name: DFlexAntOTIL
  shac:
    max_epochs: 5000
    max_agent_steps: 10000000
  otil:
    demos:
      path: "experts/demos/DFlex_ant_demos128_return9318_len1000.pt"
      n_trajs: 8
    critic_reward_mapping: exp
    imitation_loss_type: ot
    input_type: state_state
    loss_mlp_features_dim: null
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [128, 64, 32]
    critic_kwargs:
      mlp_kwargs:
        units: [64, 64]
logdir: "workdir/DFlexAnt10M-OTIL/$(date +%Y%m%d-%H%M%S.%2N)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 100

sweep:
  seed: [100, 110, 120]
  agent.otil.critic_reward_mapping: [log_exp, exp]
  # agent.otil.imitation_loss_type: [ot, l2]
  agent.otil.loss_ot_cost_type: [l2, cosine]
  agent.otil.loss_use_huber_speedup: false
  agent.otil.loss_mlp_features_dim: [null, 32, 64]
  agent.otil.loss_use_detached_prev_obs: [true, false]
