task:
  name: DFlex
  env:
    env_name: humanoid
agent:
  name: OTIL/DFlexAntSHAC
  shac:
    max_epochs: 50000
    max_agent_steps: 10000000
    critic_optim_kwargs:
      lr: 5e-4
    target_critic_alpha: 0.995
  otil:
    demos:
      path: "experts/demos/DFlex_humanoid_demos128_return8116_len984.pt"
      n_trajs: 8
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [128, 64, 32]
    critic_kwargs:
      mlp_kwargs:
        units: [64, 64]
logdir: "workdir/DFlexHumanoid10M-OTIL_SHAC/$(date +%Y%m%d-%H%M%S.%2N)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 110

sweep:
  seed: [100, 110, 120, 1000, 1100, 1200]
  agent.otil.demos.n_trajs: [1, 4, 8, 16]
  agent.otil.critic_reward_mapping: exp #[log_exp, exp]
  agent.otil.imitation_loss_type: ot
  agent.otil.loss_ot_cost_type: l2 #[l2, cosine]
  agent.otil.loss_use_huber_speedup: false
  agent.otil.loss_mlp_features_dim: null
  agent.otil.loss_use_detached_prev_obs: false


spawner:
  runtime: "7h30m"