task:
  name: Rewarped
  env:
    env_name: RollingPin
    env_suite: plasticinelab
agent:
  name: OTIL/DFlexAntSAPO
  network:
    encoder_kwargs:
      weight_init_pcd: orthogonalg1
      weight_init_mlp: orthogonalg1
      mlp_keys: "com_q|joint_q"
    actor_kwargs:
      weight_init_last_layers: False
      mlp_kwargs:
        units: [512, 256]
    critic: EnsembleCritic
    critic_kwargs:
      weight_init: orthogonalg1
      mlp_kwargs:
        units: [256, 256]
        norm_type: LayerNorm
        act_type: SiLU
      n_critics: 2
  shac:
    critic_optim_kwargs:
      lr: 5e-4
    target_critic_alpha: 0.995
    max_agent_steps: 4100000
    max_epochs: 4000
    actor_detach_encoder: False
    critic_detach_encoder: False
    share_encoder: False
  otil:
    demos:
      path: ""
      n_trajs: 8
    loss_best_of_k_k: 8
logdir: "workdir/RewarpedRollingPin4M-OTIL/$(date +%Y%m%d-%H%M%S.%2N)"
num_envs: 32
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 1200

sweep:
  seed: [100, 110, 120, 130, 140, 1000, 1100, 1200, 1300, 1400]
