task:
  name: Rewarped
  env:
    env_name: Transport
    env_suite: softgym
agent:
  name: RewarpedJumperSAPO
  network:
    encoder_kwargs:
      mlp_keys: "com_q|joint_q|target_q"
    actor_kwargs:
      mlp_kwargs:
        units: [512, 256]
    critic_kwargs:
      mlp_kwargs:
        units: [256, 256]
  otil:
    critic_optim_kwargs:
      lr: 5e-4
    target_critic_alpha: 0.995
    max_agent_steps: 4100000
    max_epochs: 4000
logdir: "workdir/Exp12W-RewarpedSoftgymTransport4M-SAPO/$(date +%Y%m%d-%H%M%S.%2N)"
num_envs: 32
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 1500
