task:
  name: DFlex
  env:
    env_name: hopper
    no_grad: true
agent:
  name: OOPS/DFlexAnt
  ddpg:
    max_agent_steps: 10000000
    horizon_len: 1000 # must match the demos' episode length
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [128, 64, 32]
    critic_kwargs:
      mlp_kwargs:
        units: [64, 64]
  oops:
    demos:
      path: "experts/demos/DFlex_hopper_demos128_return4812_len1000.pt"
      n_trajs: 8
      subsample_factor: 1
logdir: "workdir/DFlexHopper10M-OOPS/$(date +%Y%m%d-%H%M%S.%2N)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 130

sweep:
  seed: [100, 110, 120]
  agent.oops.sinkhorn_eps: [0.01, 0.05, 0.1]
  agent.oops.reward_scale: [1.0, 5.0, 10.0]
  agent.oops.state_action: [true, false]
  agent.oops.aug_time: [true, false]

spawner:
  runtime: "3h30m"
