task:
  name: DFlex
  env:
    env_name: ant
    no_grad: true
agent:
  name: DAC/DFlexAnt
  sac:
    max_agent_steps: 10000000
    +target_entropy_scalar: 0.5
    tau: 0.005
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [128, 64, 32]
    critic_kwargs:
      mlp_kwargs:
        units: [64, 64]
  dac:
    demos:
      path: "experts/demos/DFlex_ant_demos128_return9318_len1000.pt"
      n_trajs: 8
      subsample_factor: 20 # 0 means no subsampling, >1 means subsample by this factor
    input_type: state_state
    disc_update_freq: 5
    discriminator:
      iters: 1
      mlp_kwargs:
        units: [64, 64]
        norm_type: LayerNorm
        act_type: SiLU
      optim:
        type: Adam
        kwargs: { lr: 3e-4 }
    expert_batch_size: 2048
    policy_batch_size: 2048
    reward_scale: 1.0
    label_smooth: 0.0

logdir: "workdir/DFlexAnt10M-DAC/$(date +%Y%m%d-%H%M%S.%2N)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 100

sweep:
  seed: [100, 110, 120]
  agent.dac.demos.subsample_factor: [1, 20]
  agent.dac.disc_update_freq: [5, 10]
  agent.dac.expert_batch_size: 512
  agent.dac.discriminator.iters: [1, 5]
  agent.dac.discriminator.mlp_kwargs.units: [[64, 64], [128, 128]]
  agent.dac.inverse_model.enabled: true
  agent.dac.inverse_model.reg_coef: 1
  agent.dac.inverse_model.batch_size: 512
  agent.dac.inverse_model.iters: 100

spawner:
  runtime: "4h"
