defaults:
  - /agent/PPO/DFlexAnt@_here_

seed: ${..seed}
algo: GAIL

gail:
  demos:
    path: ""
    n_trajs: 8
    subsample_factor: 20 # 0 means no subsampling, >1 means subsample by this factor

  # discriminator network
  input_type: state_state # 'state', 'state_action', or 'state_state'
  disc_update_freq: 3 # frequency (in epochs) to update discriminator
  discriminator:
    iters: 1
    mlp_kwargs:
      units: [64, 64]
      norm_type: LayerNorm
      act_type: SiLU
    encoder_kwargs: null
    optim:
      type: Adam
      kwargs: { lr: 3e-4 }

  expert_batch_size: 2048
  policy_batch_size: 2048
  reward_scale: 1.0
  label_smooth: 0.0

  inverse_model:
    enabled: false
    reg_coef: 0.1
    update_freq: 1
    batch_size: 256
    iters: 1
    patience: 0 # 0 disables early stop
    min_delta: 0.0
    mlp_kwargs:
      units: [256, 256]
      norm_type: LayerNorm
      act_type: SiLU
    encoder_kwargs: null
    optim:
      type: Adam
      kwargs: { lr: 3e-4 }
