task:
  name: DFlex
  env:
    env_name: ant
agent:
  name: ILD/DFlexAnt
  shac:
    max_epochs: 5000
    max_agent_steps: 10000000
  ild:
    demos:
      path: "experts/demos/DFlex_ant_demos128_return9318_len1000.pt"
      n_trajs: 8
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [128, 64, 32]
    critic_kwargs:
      mlp_kwargs:
        units: [64, 64]
logdir: "workdir/DFlexAnt10M-ILD/$(date +%Y%m%d-%H%M%S.%2N)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 100

sweep:
  seed: [100, 110, 120]
  agent.shac.horizon_len: [5, 10, 32]

spawner:
  runtime: "3h30m"
