task:
  name: DFlex
  env:
    env_name: ant
agent:
  name: ILD/DFlexAntSAPO
  shac:
    max_epochs: 50000
    max_agent_steps: 10000000
  ild:
    demos:
      path: "experts/demos/DFlex_ant_demos128_return9318_len1000.pt"
      n_trajs: 8
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [128, 64, 32]
    critic_kwargs:
      mlp_kwargs:
        units: [64, 64]
logdir: "workdir/DFlexAnt10M-ILD/$(date +%Y%m%d-%H%M%S.%2N)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 100

sweep:
  seed: [100, 110, 120, 1000, 1100, 1200]
  agent.ild.demos.n_trajs: [1, 4, 8, 16]
  agent.shac.horizon_len: [10, 32]

spawner:
  runtime: "3h30m"
