task:
  name: DFlex
  env:
    env_name: snu_humanoid
agent:
  name: BPTT/DFlexAnt
  bptt:
    max_epochs: 5000
    max_agent_steps: 10000000
  network:
    actor_kwargs:
      mlp_kwargs:
        units: [512, 256]
logdir: "workdir/DFlexSNUHumanoid10M-BPTT/$(date +%Y%m%d-%H%M%S)"
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 120

sweep:
  seed: [100, 110, 120, 130, 140]
