task:
  name: Rewarped
  env:
    env_name: RollingPin
    env_suite: plasticinelab
agent:
  name: BPTT/RewarpedJumper
  network:
    encoder_kwargs:
      mlp_keys: "com_q|joint_q"
    actor_kwargs:
      mlp_kwargs:
        units: [512, 256]
  bptt:
    max_agent_steps: 4100000
    max_epochs: 4000
logdir: "workdir/RewarpedRollingPin4M-BPTT/$(date +%Y%m%d-%H%M%S)"
num_envs: 32
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 1200

sweep:
  seed: [100, 110, 120, 130, 140]

spawner:
  skip: true
  runtime: "2-00:00:00"
