task:
  name: Rewarped
  env:
    env_name: Jumper
    env_suite: gradsim
agent:
  name: BPTT/RewarpedJumper
  network:
    encoder_kwargs:
      mlp_keys: "com_q|com_qd|actions"
    actor_kwargs:
      mlp_kwargs:
        units: [512, 256]
logdir: "workdir/RewarpedJumper6M-BPTT/$(date +%Y%m%d-%H%M%S)"
num_envs: 32
wandb:
  mode: online
  project: rewarped
run: train_eval
seed: 1300

sweep:
  seed: [100, 110, 120, 130, 140]

spawner:
  runtime: "2-00:00:00"
